### ISSUE TITLE
OnRollback event

### ISSUE THREAD

**Issue by janslav** [jbakic/Shielded#11]
When transactions are rolled back, I think it makes sense user code should have a chance to react. Typically to log it, and/or to keep statistics about transaction success. 
I don't see how to do this currently other than looking for TransException inside Shield.InTransaction action, which doesn't seem the most healthy way.

**Comment by jbakic** [comment]
You can make your own method like InTransaction, which will first call Shield.SideEffect(null, () => { ... }); and then the main action. Perhaps a general event could be added, but I've tried to keep things simple and leave anything out that could relatively easily be implemented on top of the library.

**Comment by janslav** [comment]
Sorry somehow I dailed to notice there's a OnRollback action in the side effect call, thought there was just OnCommit one. Nvm then :)
