### ISSUE TITLE
Please give examples of using with System.Collections.Immutable

### ISSUE THREAD

**Issue by AceHack** [jbakic/Shielded#16]
Would love some examples here.

**Comment by jbakic** [comment]
Hello again :) OK, can do.

In case you're interested in an answer right now, the usage is rather simple. Immutable collections have operations which return a new collection where the operation is applied. You take this result and write it into a Shielded<> container as its new value. So:

```csharp
var a = new Shielded<ImmutableList<int>>(ImmutableList<int>.Empty);
// reading
var val = a.Value;
// writing
Shield.InTransaction(() => a.Value = a.Value.Add(5));
// via Modify. Commute would look the same
Shield.InTransaction(() => a.Modify((ref ImmutableList<int> x) => x = x.Add(5)));
```
