### ISSUE TITLE
Error with NuGet version

### ISSUE THREAD

**Issue by ocozalp** [jbakic/Shielded#4]
I'm getting a NullReferenceException with the current NuGet version. 
Full stack trace is ;

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.`
`   at Shielded.Shielded1.CurrentTransactionOldValue()`
`   at Shielded.Shielded1.get_Value()`
`   at Shielded.Shielded1.op_Implicit(Shielded1 obj)`
`   at STM.Program.<run>b__2() `
`   at Shielded.Shield.<InTransaction>c__AnonStorey41.<>m__0()`
`   at Shielded.Shield.InTransaction(Action act)`
`   at Shielded.Shield.InTransaction[T](Func1 act)`
`   at STM.Program.run() `
`   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)`
`   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)`
`   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)`
`   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)`
`   at System.Threading.ThreadHelper.ThreadStart()`

My code is below. The same code works fine with the Shielded version I compiled from github.

```c#
namespace STM
{
    class Program   
    {
        private static Shielded.Shielded<int> counter = new Shielded.Shielded<int>(0);

        static void Main(string[] args)
        {
            var thread1 = new Thread(run);
            var thread2 = new Thread(run);

            thread1.Start();
            thread2.Start();

            thread1.Join();
            thread2.Join();

            Shielded.Shield.InTransaction(
                () =>
                    Console.WriteLine(counter.Value)
                );
            
        }

        private static void run()
        {
            for (int i = 0; i < (int)1e4; i++)
            {
                Shielded.Shield.InTransaction(
                    () =>
                        {
                            counter.Value = counter + 1;
                        }
                    );
            }
        }
    }
}
```

**Comment by jbakic** [comment]
Hi!

I am unable to reproduce the issue. Could you tell me what platform you are running your tests on? The DLL in the package was built with Mono 3.12, on Linux, I presume you are on Windows / MS.NET? I have tried your code in a VM on Windows too, with VS 2013, using the package that was published, and still it worked.

The exception comes from trying to read a version of data that was trimmed away (the system wrongly concluded that it is safe to remove an older version of data which one of the threads then tries to read). It is possible that a subtle bug exists in one of the methods there, either the trimming or, more likely, the method which gives out reading tickets. The ILs generated by VS and Mono are different, which might explain why the bug goes away (at least seemingly) when you build it yourself.

How easily can you reproduce this? I have some ideas about what to try out, but being unable to reproduce, I cannot confirm if anything helps. I would like to email you some alternate versions of the DLL. If you have the time to try them out, I would be grateful. If yes, pls give me an email address where I can send this (I don't see a file attach option here...).

**Comment by ocozalp** [comment]
Hi, 

I had the exception almost every time, but some of my trials were successful. I used .NET versions 4.0 and 4.5.1, 32-bit, 64-bit & Any-CPU options but all of the combinations gave the same results. 

I'm using Windows 7 and VS 2013.

I took a brief look at the decompiled code with dotPeek but couldn't see any differences. Maybe it is better to try with different DLLs as you said. You can send the DLLs to ozalp.orhan at gmail dot com. I will try and send the results back to you.
