### ISSUE TITLE
Transaction priority

### ISSUE THREAD

**Issue by janslav** [jbakic/Shielded#8]
I'm not completely familiar with the principle of deciding who gets rolled back, but would it be possible to implement a priority, or at least a "primary/nonprimary" flag (where there could be just one primary transaction running at a time)?
Maybe I'd be willing to try implementing this myself if you could point me in the correct direction... :)

**Comment by jbakic** [comment]
There's one implementation of the primary/non-primary thing here: https://github.com/jbakic/Shielded/blob/master/ShieldedTests/PreCommitTests.cs#L87 -- advantage is that the pre-commit op will "automatically" execute within every transaction that touches certain fields. Its big flaw is that it causes the non-primary transactions to repeatedly roll back, busy-waiting for the primary to end. This can be improved, perhaps by simply acquiring a lock before running the primary, and then having the pre-commit lambda wait on it. The primary can then pulse after committing. This should be perfectly safe.

Would you like to improve that test in the Shielded lib? Contributions are welcome :)

**Comment by janslav** [comment]
Yeah that looks like what I was talking about, I'll have a look there :)
